'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');const {chromium}=require(process.env.ROBOS_PLAYWRIGHT_MODULE||'playwright-core');
test('visual editor formats Markdown and AI description defaults on, remains editable and restores prior text',async()=>{
 const b=await chromium.launch({headless:true});try{const p=await b.newPage();await p.setContent('<input id="title" value="Filters"><div id="ai"></div><review-markdown-editor></review-markdown-editor>');await require('./editor-test-helper')(p);
 await p.addScriptTag({path:path.resolve(__dirname,'../../../pr-review/renderer/ai-description.js')});await p.evaluate(()=>{window.api={generatePRDescription:async()=>({ok:true,markdown:'## Changes\n\n**Compact filters**\n\n- Verified filtering',warnings:['Screenshot upload needed.']})};const body=document.querySelector('review-markdown-editor');body.value='Original description';window.ai=window.mountAIDescription(document.getElementById('ai'),{pr:{},title:document.getElementById('title'),body,saved:{},save:()=>{}});});
 assert.equal(await p.getByRole('checkbox').isChecked(),true);await p.evaluate(()=>window.preparePRDescription());await p.getByRole('status').filter({hasText:'AI description ready'}).waitFor();
 assert.equal(await p.locator('.toastui-editor-ww-container h2').innerText(),'Changes');assert.equal(await p.locator('.toastui-editor-ww-container strong').innerText(),'Compact filters');
 assert.match(await p.locator('review-markdown-editor').evaluate(el=>el.value),/\*\*Compact filters\*\*/);
 await p.getByRole('button',{name:'Restore previous description'}).click();assert.equal(await p.locator('review-markdown-editor').evaluate(el=>el.value),'Original description');assert.equal(await p.getByRole('checkbox').isChecked(),false);
 await p.getByRole('textbox',{name:'Description',exact:true}).press('ControlOrMeta+A');await p.getByRole('button',{name:'Bold',exact:true}).click();assert.equal(await p.locator('review-markdown-editor').evaluate(el=>el.value),'**Original description**');
 await p.evaluate(()=>{window.api.generatePRDescription=()=>new Promise(resolve=>window.resolveDescription=resolve);});await p.getByRole('checkbox').check();await p.getByRole('textbox',{name:'Description',exact:true}).fill('Human edit while generating');await p.evaluate(()=>window.resolveDescription({ok:true,markdown:'Stale AI text',warnings:[]}));await p.getByRole('status').filter({hasText:'Your edits were kept'}).waitFor();assert.equal(await p.locator('review-markdown-editor').evaluate(el=>el.value),'**Human edit while generating**');
 }finally{await b.close();}
});
