'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {DemoSession,validateProcess}=require('../../../pr-review/lib/demo-session');
function session(run){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'demo-session-test-'));const file=path.join(dir,'process.json');fs.writeFileSync(file,JSON.stringify({instructions:'Use local dev mode and Chrome DevTools MCP',checkpoints:[{title:'One',given:'Ready',when:'Open',then:'Visible'},{title:'Two',given:'Open',when:'Click',then:'Changed'}]}));return new DemoSession({workspace:dir,processFile:file},run);}
test('start pauses at one checkpoint; only Next advances',async()=>{const prompts=[];const s=session(async p=>{prompts.push(p);return {reply:'Observed',checkpointReached:true};});await s.act('start');assert.equal(s.index,0);assert.equal(s.status,'paused');await s.act('explain');assert.equal(s.index,0);assert.match(prompts[1],/Do not edit code or move the browser/);await s.act('message','Make the label shorter');assert.equal(s.index,0);assert.match(prompts[2],/Make the label shorter/);await s.act('next');assert.equal(s.index,1);await assert.rejects(s.act('next'),/final checkpoint/);});
test('failed assertion does not advance and Retry targets failed checkpoint',async()=>{let pass=true;const s=session(async()=>({reply:'result',checkpointReached:pass}));await s.act('start');pass=false;await s.act('next');assert.equal(s.index,0);assert.equal(s.status,'error');await assert.rejects(s.act('next'),/Reach/);pass=true;await s.act('retry');assert.equal(s.index,1);});
test('startup failure can be retried without skipping first checkpoint',async()=>{let fail=true;const s=session(async()=>{if(fail)throw Error('Chrome unavailable');return {reply:'ready',checkpointReached:true};});await s.act('start');assert.equal(s.index,-1);assert.equal(s.status,'error');fail=false;await s.act('retry');assert.equal(s.index,0);});
test('concurrent actions and process edits are refused',async()=>{let release;const s=session(()=>new Promise(r=>release=r));const run=s.act('start');await assert.rejects(s.act('next'),/already working/);assert.throws(()=>s.saveProcess(s.process),/Wait/);release({reply:'Ready',checkpointReached:true});await run;});
test('process customization validates and resets state, persists to disk',async()=>{const s=session(async()=>({reply:'Ready',checkpointReached:true}));await s.act('start');assert.throws(()=>s.saveProcess({instructions:'bad',checkpoints:[]}),/at least one/);s.saveProcess({...s.process,instructions:'Different flow'});assert.equal(s.index,-1);assert.equal(s.status,'idle');assert.equal(JSON.parse(fs.readFileSync(s.processFile)).instructions,'Different flow');});
test('malformed agent results never claim checkpoint readiness',async()=>{const s=session(async()=>({reply:'all good'}));await s.act('start');assert.equal(s.status,'error');assert.equal(s.index,-1);});
test('empty messages and unknown actions are rejected',async()=>{const s=session(async()=>({reply:'ready',checkpointReached:true}));await s.act('start');await assert.rejects(s.act('message',' '),/Enter a message/);await assert.rejects(s.act('merge'),/Unknown/);});
test('checkpoint schema requires intentions and expected outcomes',()=>{assert.throws(()=>validateProcess({instructions:'demo',checkpoints:[{title:'x'}]}),/given/);});
test('agent executable receives structured-output paths and returns a real process result',async()=>{
 const s=session();s.agent={command:process.execPath,args:['-e',`const fs=require('node:fs');const a=process.argv;const out=a[a.indexOf('--output-last-message')+1];let input='';process.stdin.on('data',x=>input+=x);process.stdin.on('end',()=>fs.writeFileSync(out,JSON.stringify({reply:input.includes('Checkpoint 1/2')?'context received':'missing',checkpointReached:true})));`,'--'],timeoutMs:2000};
 await s.act('start');assert.equal(s.status,'paused');assert.equal(s.messages.at(-1).text,'context received');
});
test('timeout cannot advance progress',async()=>{const s=session();s.agent={command:process.execPath,args:['-e','setInterval(()=>{},1000)','--'],timeoutMs:30};await s.act('start');assert.equal(s.index,-1);assert.equal(s.status,'error');assert.match(s.messages.at(-1).text,/timed out/);});
test('missing executable is reported without becoming a ready checkpoint',async()=>{const s=session();s.agent={command:'/nonexistent/robos-test-agent',args:[],timeoutMs:1000};await s.act('start');assert.equal(s.status,'error');assert.equal(s.index,-1);});
