'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium}=require(process.env.ROBOS_PLAYWRIGHT_MODULE || 'playwright-core');
const {DemoSession}=require('../../../pr-review/lib/demo-session');
test('Start over toolbar resets a completed walkthrough and blocks duplicate actions',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'restart-ui-'));const file=path.join(dir,'process.json');
 fs.writeFileSync(file,JSON.stringify({instructions:'Test fixture process',checkpoints:[{title:'First',given:'Initial',when:'Open',then:'Ready'},{title:'Last',given:'Ready',when:'Continue',then:'Done'}]}));
 // Test double for the external model; real session state machine and renderer.
 const session=new DemoSession({workspace:dir,processFile:file},async()=>({reply:'Test checkpoint',checkpointReached:true}));
 await session.act('start');await session.act('next');
 const browser=await chromium.launch({headless:true});
 try {
  const page=await browser.newPage();await page.addStyleTag({path:path.resolve(__dirname,'../../../pr-review/renderer/style.css')});await page.setContent('<section id="stage-6"></section>');
  await page.exposeFunction('readDemo',()=>session.state());
  await page.exposeFunction('actDemo',async opts=>({ok:true,state:await session.act(opts.action,opts.text)}));
  await page.evaluate(()=>{window.api={getDemoState:window.readDemo,demoAction:window.actDemo,onDemoState:fn=>window.updateDemo=fn};});
  session.on('state',state=>page.evaluate(s=>window.updateDemo(s),state));
  await page.addScriptTag({path:path.resolve(__dirname,'../../../robos-ui/robos-ui.js')});
  await page.addScriptTag({path:path.resolve(__dirname,'../../../pr-review/renderer/demo-ui.js')});await page.evaluate(()=>window.mountWalkthrough());
  await page.addStyleTag({path:path.resolve(__dirname,'../../../pr-review/renderer/style.css')});
  let finish;session.runAgent=()=>new Promise(r=>finish=r);
  await page.getByText('More',{exact:true}).click();
  await page.getByRole('button',{name:'Start over',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.walkthrough-status').textContent==='In progress');
  assert.equal(await page.locator('.walkthrough-more').isVisible(),false);
  assert.equal(await page.locator('.walkthrough-bar button:visible').count(),0);
  session.reportProgress('Checking that the saved compact filters appear in Build History.');
  await page.getByRole('log').getByText('Checking that the saved compact filters appear in Build History.',{exact:true}).waitFor();
  assert.match(await page.locator('.walkthrough-progress small').textContent(),/elapsed/);
  assert.equal(await page.locator('.walkthrough-progress details').count(),0);
  session.handleAgentEvent({type:'item.started',item:{type:'command_execution',command:'opaque'}});
  assert.match(await page.locator('.walkthrough-progress [role=status]').textContent(),/saved compact filters/);
  finish({reply:'First checkpoint ready',checkpointReached:true});
  await page.waitForFunction(()=>document.querySelector('.walkthrough-status').textContent==='Paused · 1/2');
  assert.equal(await page.locator('.walkthrough-checkpoint h3').textContent(),'First');
  assert.equal(await page.locator('.walkthrough-progress').isVisible(),false);
  assert.match(await page.getByRole('log').textContent(),/Start over: First/);
  assert.equal(await page.getByRole('button',{name:'Next checkpoint →',exact:true}).isEnabled(),true);
  const composer=page.getByRole('textbox',{name:'Message the demo agent'});
  assert.equal(await page.locator('.walkthrough-compose robos-ai-textarea').count(),1);
  const small=(await composer.boundingBox()).height;
  await composer.fill(Array(30).fill('Please explain this change.').join('\n'));
  const large=(await composer.boundingBox()).height;assert.ok(large>small);assert.ok(large<=300);
  await composer.fill('Please explain the current filter.');await composer.press('Control+Enter');
  await page.waitForFunction(()=>document.querySelector('.walkthrough-status').textContent==='In progress');
  assert.equal(session.messages.filter(m=>m.role==='user').at(-1).text,'Please explain the current filter.');
  assert.equal(await composer.innerText(),'');
  assert.equal(await page.locator('.walkthrough-receipt').isVisible(),false);
  session.reportProgress('Inspecting the Filters click handler before changing it.');
  await page.getByRole('log').locator('.progress-entry').filter({hasText:'Inspecting the Filters click handler'}).waitFor();
  session.reportProgress('Verifying that advanced controls disappear when Filters is clicked again.');
  await page.getByRole('log').locator('.progress-entry').filter({hasText:'Verifying that advanced controls disappear'}).waitFor();
  const count=session.messages.length;await composer.press('Control+Enter');assert.equal(session.messages.length,count);
  await composer.fill('Keep this next draft.');finish({reply:'Explained',checkpointReached:true});
  await page.waitForFunction(()=>document.querySelector('.walkthrough-status').textContent.startsWith('Paused'));
  assert.equal(await composer.innerText(),'Keep this next draft.');
 } finally {session.removeAllListeners();await browser.close();}
});
