'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');const {chromium}=require(process.env.ROBOS_PLAYWRIGHT_MODULE||'playwright-core');
test('skills browse/search/preview inserts actual instructions and text never overlaps toolbar',async()=>{
 const b=await chromium.launch({headless:true});try{const p=await b.newPage();await p.setContent('<robos-ai-textarea show-agent="false"></robos-ai-textarea>');await p.evaluate(()=>window.api={listSkills:async()=>({ok:true,skills:[{id:'review',name:'Review code',description:'Inspect changes carefully',category:'Development',instructions:'Read the diff and verify the behavior.'},{id:'graph',name:'Inspect graph',description:'Explore architecture',category:'Graph',instructions:'Inspect the graph.'}]})});await p.addScriptTag({path:path.resolve(__dirname,'../../../robos-ui/robos-ui.js')});
 assert.equal(await p.locator('.robos-ai-toolbar .robos-security-badge').count(),0);
 await p.getByRole('button',{name:'/skills',exact:true}).click();await p.getByRole('searchbox',{name:'Search skills'}).fill('carefully');await p.getByRole('button',{name:'Review code Inspect changes carefully'}).click();await p.getByRole('button',{name:'Add to prompt',exact:true}).click();assert.match(await p.locator('robos-ai-textarea').evaluate(e=>e.value),/Read the diff and verify the behavior/);
 await p.locator('robos-ai-textarea').evaluate(e=>e.value='Long text\n'.repeat(100));const bounds=await p.evaluate(()=>({editor:document.querySelector('.robos-ai-inner').getBoundingClientRect().bottom,toolbar:document.querySelector('.robos-ai-toolbar').getBoundingClientRect().top}));assert.ok(bounds.editor<=bounds.toolbar);
 await p.getByRole('button',{name:'/skills',exact:true}).click();await p.getByRole('searchbox',{name:'Search skills'}).fill('nonexistent');await p.getByRole('status').filter({hasText:'No matching skills'}).waitFor();await p.keyboard.press('Escape');await p.getByRole('dialog',{name:'Browse RobOS skills'}).waitFor({state:'hidden'});
 }finally{await b.close();}
});
