'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {spawn}=require('node:child_process');
const {_electron:electron}=require('playwright-core');
const {GraphWorkspace,hash}=require('../../../robos-graph/lib/graph-workspace');
const {plans,viewPlan}=require('../../../task-planner/lib/project-plan');
test('real GitHub plan: Task Planner preview/save/reopen and KGraph task 48 Project Plan', {timeout:180000,skip:!process.env.ROBOS_PLAN_E2E_ROOT},async()=>{
 const original=process.env.ROBOS_PLAN_E2E_ROOT,proof=process.env.ROBOS_GRAPH_PROOF_ROOT;
 assert.ok(proof,'Set proof directory outside RobOS');fs.mkdirSync(proof,{recursive:true});
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'plan-e2e-'));fs.cpSync(path.join(original,'.robos'),path.join(root,'.robos'),{recursive:true});
 const originalHash=hash(new GraphWorkspace(original).read());
 const live=viewPlan(root,'48','Hermetiq/task-and-issue-tracking');assert.equal(live.issue.number,48);
 fs.writeFileSync(path.join(proof,'live-task-48.json'),JSON.stringify(live,null,2));
 const ws=new GraphWorkspace(root),initial=hash(ws.read());const captions=[],start=Date.now();
 const recorder=spawn('ffmpeg',['-loglevel','error','-y','-f','x11grab','-video_size','1920x1080','-framerate','15','-i',process.env.DISPLAY,'-c:v','libvpx-vp9','-deadline','realtime','-cpu-used','8',path.join(proof,'project-plans.webm')],{stdio:['pipe','ignore','pipe']});
 let recorderError='';recorder.stderr.on('data',b=>recorderError+=b);let app;
 const launch=name=>electron.launch({executablePath:process.env.ELECTRON_BIN||require('electron'),args:[path.resolve(__dirname,`../../../${name}/main.js`),'--no-sandbox','--disable-gpu','--disable-dev-shm-usage'],env:{...process.env,ROBOS_GRAPH_ROOT:root,ROBOS_TEST:'1'}});
 const narrate=async(page,text)=>{captions.push({time:(Date.now()-start)/1000,text});await page.evaluate(text=>{let e=document.getElementById('proof-caption');if(!e){e=document.createElement('div');e.id='proof-caption';e.style.cssText='position:fixed;bottom:10px;left:20px;right:20px;z-index:99999;background:#163440;color:white;padding:16px;border:2px solid #00bcd4;font:18px sans-serif;pointer-events:none';document.body.append(e);}e.textContent=text;},text);await page.waitForTimeout(900);};
 try{
  app=await launch('task-planner');let page=await app.firstWindow();
  await page.locator('#server-badge').filter({hasText:'Hermetiq/task-and-issue-tracking'}).waitFor();
  await page.locator('#btn-workspace-plans').click();await page.getByLabel('Project plan',{exact:true}).waitFor();
  await narrate(page,'Task Planner reads the linked Hermetiq projects from the selected KGraph workspace.');
  await page.screenshot({path:path.join(proof,'01-task-planner.png')});
  const plan=plans(root).find(p=>p.id==='hermetiq-linked-project-planning');assert.ok(plan);
  plan.summary+=' Verified preview/save in an isolated copy of the official graph.';
  await page.locator('#workspace-plan-panel > details > summary').click();
  await page.locator('#workspace-plan-input').fill(JSON.stringify(plan));
  await page.locator('#workspace-plan-preview').click();
  await page.locator('#workspace-plan-save:not([disabled])').waitFor({timeout:45000});
  assert.equal(hash(ws.read()),initial);await narrate(page,'Preview reads real GitHub issue 49 and validates changes without saving the graph.');
  await page.screenshot({path:path.join(proof,'02-preview.png')});
  await page.locator('#workspace-plan-save').click();
  await page.locator('#workspace-plan-review').filter({hasText:'revision'}).waitFor();
  assert.notEqual(hash(ws.read()),initial);
  await app.close();app=await launch('task-planner');page=await app.firstWindow();await page.locator('#btn-workspace-plans').click();
  await page.getByLabel('Project plan',{exact:true}).selectOption('hermetiq-linked-project-planning');
  await page.locator('.plan-heading').filter({hasText:'Verified preview/save'}).waitFor();
  await narrate(page,'Reopening Task Planner retains the saved project plan.');await page.screenshot({path:path.join(proof,'03-reopened.png')});
  await app.close();app=await launch('robos-graph');page=await app.firstWindow();
  await page.locator('#node-search-input').fill('#48');
  await page.locator('[data-node-id="urn:hermetiq:issue:hermetiq-task-and-issue-tracking:48"]').click();
  await page.locator('#tab-btn-plan').click();await page.locator('.plan-heading').filter({hasText:'Land the Buildbarn'}).waitFor();
  await narrate(page,'Selecting task 48 exposes the same standard Project Plan in KGraph Explorer.');await page.screenshot({path:path.join(proof,'04-kgraph-project-plan.png')});
  const card=page.locator('[data-issue-url="https://github.com/Hermetiq/task-and-issue-tracking/issues/48"]');
  await card.getByText('Read current task',{exact:true}).click();
  await page.locator('.plan-card h2').filter({hasText:'Current GitHub task #48'}).waitFor({timeout:45000});
  await page.locator('#inspector-content').evaluate(e=>e.scrollTop=0);
  await narrate(page,'The viewer reads issue 48 live, while saved plans remain unchanged. The backend provenance handshake remains visible as outstanding work.');await page.screenshot({path:path.join(proof,'05-live-task-48.png')});
  assert.equal(hash(new GraphWorkspace(original).read()),originalHash);
  fs.writeFileSync(path.join(proof,'result.json'),JSON.stringify({passed:true,assertions:['real GitHub task 48 read','Task Planner lists official plans','preview does not write','save persists','reopen retains plan','KGraph task Project Plan tab','live task read','original official graph unchanged'],captions},null,2));
 }finally{if(app)await app.close();recorder.stdin.write('q');await new Promise(r=>recorder.on('close',r));const time=s=>new Date(Math.floor(s*1000)).toISOString().slice(11,23);fs.writeFileSync(path.join(proof,'project-plans.vtt'),'WEBVTT\n\n'+captions.map((c,i)=>`${i+1}\n${time(c.time)} --> ${time(captions[i+1]?.time||(Date.now()-start)/1000)}\n${c.text}\n`).join('\n'));}
 assert.equal(recorder.exitCode,0,recorderError);
});
