'use strict';
const {test}=require('node:test'), assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {GraphWorkspace,hash}=require('../../../robos-graph/lib/graph-workspace');
const {validatePlan,proposePlan,viewPlan,plans,issueIdentity,exportPlan,proposeRemovePlan}=require('../../../task-planner/lib/project-plan');
const capabilities=require('../../../robos-graph/lib/inspector-capabilities');
const url=n=>`https://github.com/example/tracker/issues/${n}`;
const input=()=>({version:1,id:'delivery',namespace:'example',name:'Delivery plan',summary:'Ship the feature',design:'Review then implement',verification:'Real application proof',owners:['Owner'],repository:'example/tracker',status:'review-required',source:{repository:'example/plans',path:'delivery.json'},items:[{url:url(1),type:'Feature',delivery:'Design and delivery'},{url:url(2),type:'Task',parent:url(1),delivery:'Implement the approved design'}]});
const fetchIssue=url=>({url,number:issueIdentity(url).number,title:'Recorded issue',body:'- [ ] Acceptance',state:'open',type:'Task',updatedAt:'2026-09-12T00:00:00Z'});
test('exact plan removal preserves all entities and shared plans; backup restores it',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'robos-plan-lifecycle-'));
 const ws=new GraphWorkspace(dir);ws.apply(ws.propose({mode:'replace',document:ws.empty('Lifecycle test')}));
 ws.apply(proposePlan(dir,input(),fetchIssue));
 ws.apply(proposePlan(dir,{...input(),id:'shared'},fetchIssue));
 const backup=exportPlan(dir,'delivery'), before=ws.read(), beforeHash=hash(before);
 assert.throws(()=>proposeRemovePlan(dir,'2'),/exact/);
 assert.throws(()=>proposeRemovePlan(dir,url(2)),/exact/);
 const proposal=proposeRemovePlan(dir,backup.graphId);
 assert.equal(proposal.validation.conforms,true);assert.equal(hash(ws.read()),beforeHash);
 ws.apply(proposal);
 assert.deepEqual(plans(dir).map(p=>p.id),['shared']);
 const expected=structuredClone(before);delete expected['robos:nodes'].find(n=>n['@id']===backup.graphId)['robos:planJson'];
 assert.deepEqual(ws.read()['robos:nodes'],expected['robos:nodes']);
 assert.equal(viewPlan(dir,'2',undefined,fetchIssue).plans[0].id,'shared');
 assert.throws(()=>proposeRemovePlan(dir,backup.graphId),/exact/);
 ws.apply(proposePlan(dir,backup,fetchIssue));assert.equal(plans(dir).length,2);
 assert.equal(viewPlan(dir,backup.graphId).plans[0].id,'delivery');
 const stale=proposeRemovePlan(dir,backup.graphId);
 ws.apply(proposePlan(dir,{...backup,summary:'Revised'},fetchIssue));
 assert.throws(()=>ws.apply(stale),/Stale/);
});
test('plan rejects ambiguous identity, unsupported versions, duplicate links and cycles',()=>{
 assert.throws(()=>issueIdentity('https://evil.test/example/tracker/issues/1'));
 assert.throws(()=>validatePlan({...input(),version:2}));
 assert.throws(()=>validatePlan({...input(),items:[input().items[0],input().items[0]]}));
 const cyclic=input();cyclic.items[0].dependsOn=[url(2)];assert.throws(()=>validatePlan(cyclic),/Cyclic/);
 const missing=input();missing.items[1].dependsOn=[url(99)];assert.throws(()=>validatePlan(missing),/Unknown/);
 assert.throws(()=>validatePlan({...input(),status:'approved'}),/approval/);
});
test('preview, atomic save, task lookup, idempotent refresh and capability gating',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'robos-plan-'));
 const ws=new GraphWorkspace(dir);ws.apply(ws.propose({mode:'replace',document:ws.empty('Plan test')}));
 const before=hash(ws.read());const proposal=proposePlan(dir,input(),fetchIssue);
 assert.equal(proposal.validation.conforms,true,JSON.stringify(proposal.validation.errors));assert.equal(hash(ws.read()),before);
 ws.apply(proposal);assert.equal(plans(dir).length,1);
 const saved=hash(ws.read());let requests=0;
 const view=viewPlan(dir,'2',undefined,u=>{requests++;return fetchIssue(u);});
 assert.equal(requests,1);assert.equal(view.issue.url,url(2));assert.equal(view.plans[0].id,'delivery');assert.equal(hash(ws.read()),saved);
 const nodes=ws.read()['robos:nodes'], project=nodes.find(n=>n['robos:planJson']),task=nodes.find(n=>n['robos:url']===url(2));
 assert.ok(capabilities.capabilities(project,nodes).tabs.includes('plan'));assert.ok(capabilities.capabilities(task,nodes).tabs.includes('plan'));
 assert.ok(!capabilities.capabilities({'@id':'urn:example:other'},nodes).tabs.includes('plan'));
 ws.apply(proposePlan(dir,input(),fetchIssue));assert.equal(hash(ws.read()),saved);
 const stale=proposePlan(dir,input(),fetchIssue);const changed=input();changed.summary='Changed scope';ws.apply(proposePlan(dir,changed,fetchIssue));assert.throws(()=>ws.apply(stale),/Stale/);
 assert.throws(()=>viewPlan(dir,'99',undefined,fetchIssue),/No saved/);
});
test('network failure prevents preview and mixed repositories require disambiguation',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'robos-plan-'));
 const ws=new GraphWorkspace(dir);ws.apply(ws.propose({mode:'replace',document:ws.empty('Plan test')}));
 assert.throws(()=>proposePlan(dir,input(),()=>{throw new Error('GitHub unavailable');}),/unavailable/);assert.equal(plans(dir).length,0);
 ws.apply(proposePlan(dir,input(),fetchIssue));
 const second=input();second.id='other';second.repository='example/another';second.items=second.items.map(i=>({...i,url:i.url.replace('/tracker/','/another/'),...(i.parent?{parent:i.parent.replace('/tracker/','/another/')}:{})}));
 ws.apply(proposePlan(dir,second,fetchIssue));assert.throws(()=>viewPlan(dir,'2'),/ambiguous/);
});
