// Canonical site facts shared by metadata, robots.txt, sitemap.xml, JSON-LD, OG images and llms.txt.
// Generated by the RobOS App Wizard (template: nextjs-vercel-web). Edit freely.
export const SITE_URL = 'https://www.urbanplanttracker.com';
export const SITE_NAME = "Urban Plant Tracker";
export const SITE_INITIALS = "UP";
export const TAGLINE = "Keep your green friends thriving effortlessly.";
export const DESCRIPTION = "Smart indoor plant care companion with automated watering reminders, botanical light logs, and care guides.";
export const SHORT_DESCRIPTION = "Keep your green friends thriving effortlessly.";
export const KEYWORDS = ["plants","botanical","care","gardening"];
export const THEME = { background: '#0c0a12', accent: '#ff3d7f', accent2: '#ffd23f' };
// Swap to '/hero.gif' after recording one from your E2E run (scripts/make-hero-gif.sh).
export const HERO_IMAGE = '/hero.svg';

export const FAQ = [
  ['Is it free?', 'Yes — creating an account is free.'],
  ['Does it work on my phone?', `Yes. ${SITE_NAME} is built phone-first; add it to your home screen and it works like an app.`],
  ['How do I delete my account?', 'Open Account and use “Delete my account”. Your data is removed permanently.'],
];

/** Public pages listed in sitemap.xml (add yours). */
export const PUBLIC_PAGES = [
  { path: '/', changeFrequency: 'daily', priority: 1 },
  { path: '/signup', changeFrequency: 'monthly', priority: 0.6 },
  { path: '/terms', changeFrequency: 'yearly', priority: 0.2 },
  { path: '/privacy', changeFrequency: 'yearly', priority: 0.2 },
];

/** Private / per-user paths: disallowed in robots.txt and marked noindex. */
export const PRIVATE_PATHS = ['/api/', '/dashboard', '/account'];
export const NO_INDEX = { index: false, follow: false, nocache: true, googleBot: { index: false, follow: false } };
